apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
  namespace: default
spec:
  refreshInterval: "15s" # How often ESO checks LocalStack for updates
  secretStoreRef:
    name: localstack-backend
    kind: SecretStore
  target:
    name: k8s-app-db-secret # This is the native secret your app pods will mount
    creationPolicy: Owner
  data:
  - secretKey: DB_USER # Key inside the final K8s secret
    remoteRef:
      key: "production/database/credentials"
      property: username # Key inside the LocalStack JSON payload
  - secretKey: DB_PASS
    remoteRef:
      key: "production/database/credentials"
      property: password