apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: localstack-backend
  namespace: default
spec:
  provider:
    aws:
      region: us-east-1
      service: SecretsManager
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-credentials
            key: aws-access-key-id
          secretAccessKeySecretRef:
            name: localstack-credentials
            key: aws-secret-access-key