apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-frontend-sa
  namespace: vote-app
automountServiceAccountToken: false # Production standard: Do not leak tokens inside the container
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: vote-app
automountServiceAccountToken: false # Production standard: Keep identity locked down