
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: redis-sa # 👈 Bound identity
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-frontend
  namespace: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-frontend
  template:
    metadata:
      labels:
        app: vote-frontend
    spec:
      serviceAccountName: vote-frontend-sa # 👈 Bound identity
      containers:
      - name: vote
        image: dockersamples/examplevotingapp_vote:before # playground app
        ports:
        - containerPort: 80
          name: vote